# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Grafana Changes 📊
      labels:
        - "grafana"
    - title: Prometheus Changes 🔥
      labels:
        - "prometheus"
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
