name: trunk-cd

on:
  push:
    paths:
      - 'VERSION'
  workflow_dispatch:

jobs:

  build-and-push-image:
    name: Build and push container image to GHCR
    runs-on: ubuntu-latest
    outputs:
      version-meshtastic: ${{ steps.version-meshtastic.outputs.version }}
      our-version-major: ${{ steps.our-version-major.outputs.version }}
      our-version-minor: ${{ steps.our-version-minor.outputs.version }}
      our-version-full: ${{ steps.our-version-full.outputs.version }}
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: version-meshtastic
        run: |
          echo version=$(cat VERSION_MESHTASTIC) >> $GITHUB_OUTPUT

      - id: our-version-major
        run: |
          echo version=$(cat VERSION | cut -d '.' -f 1) >> $GITHUB_OUTPUT

      - id: our-version-minor
        run: |
          echo version=$(cat VERSION | cut -d '.' -f 2) >> $GITHUB_OUTPUT

      - id: our-version-full
        run: |
          echo version=${{ steps.version-meshtastic.outputs.version }}-${{ steps.our-version-major.outputs.version }}.${{ steps.our-version-minor.outputs.version }} >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.our-version-full.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.version-meshtastic.outputs.version }}-${{ steps.our-version-major.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.our-version-major.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.our-version-major.outputs.version }}.${{ steps.our-version-minor.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:latest

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          CUSTOM_TAG: ${{ needs.build-and-push-image.outputs.our-version-full }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: Meshtastic Prometheus Exporter ${{ needs.build-and-push-image.outputs.our-version-full }} Alpha
          tag_name: ${{ needs.build-and-push-image.outputs.our-version-full }}
          generate_release_notes: true
          token: ${{ github.token }}
