#name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI
name: trunk

on: push

jobs:
  test-cs:
    name: Test code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  build-and-push-image:
    name: Build and push container image to GHCR
    runs-on: ubuntu-latest
    outputs:
      version-meshtastic: ${{ steps.version-meshtastic.outputs.version }}
      our-version-major: ${{ steps.our-version-major.outputs.version }}
      our-version-minor: ${{ steps.our-version-minor.outputs.version }}
      our-version-full: ${{ steps.our-version-full.outputs.version }}
    needs:
      - test-cs
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: version-meshtastic
        run: |
          echo version=$(cat VERSION_MESHTASTIC) >> $GITHUB_OUTPUT

      - id: our-version-major
        run: |
          echo version=$(cat VERSION | cut -d '.' -f 1) >> $GITHUB_OUTPUT

      - id: our-version-minor
        run: |
          echo version=$(cat VERSION | cut -d '.' -f 2) >> $GITHUB_OUTPUT

      - id: our-version-full
        run: |
          echo version=${{ steps.version-meshtastic.outputs.version }}-${{ steps.our-version-major.outputs.version }}.${{ steps.our-version-minor.outputs.version }} >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.our-version-full.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:${{ steps.version-meshtastic.outputs.version }}-${{ steps.our-version-major.outputs.version }}
            ghcr.io/artiommocrenco/meshtastic-prometheus-exporter:latest
